services:
  fnosqbit2xunlei:
    image: chhc007/fnos-qbit2xunlei:latest
    container_name: fnosqbit2xunlei
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /vol4/1000/DockerConfig/fnosqbit2xunlei/config:/app/config