services:
  fnosqbit2xunlei:
    build: .
    container_name: fnosqbit2xunlei
    restart: unless-stopped
    volumes:
      - ./config:/app/config
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
